<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KUCY2QTP01" name="com.PaymentCenterTestCases.PaymentCenterTestClass" tests="10" failures="5" timestamp="22 Apr 2016 11:34:21 GMT" time="171.580" errors="0">
  <testcase name="Scenario_2_LaunchPaymentCenter_from_Portal_Make_CC_Payment" time="4.875" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <failure type="java.lang.AssertionError" message="Exception thrown, logout from  Admin KU Portal. Excep Msg&#039;Webmail&#039; column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown, logout from  Admin KU Portal. Excep Msg'Webmail' column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.logintoAdminPortal_Reset_Password(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_2_LaunchPaymentCenter_from_Portal_Make_CC_Payment(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- Scenario_2_LaunchPaymentCenter_from_Portal_Make_CC_Payment -->
  <testcase name="Scenario_5_FeeTypePaymentFromEmployeeSite" time="4.734" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <failure type="java.lang.AssertionError" message="Exception thrown, logout from  Admin KU Portal. Excep Msg&#039;Webmail&#039; column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown, logout from  Admin KU Portal. Excep Msg'Webmail' column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.logintoAdminPortal_Reset_Password(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_5_FeeTypePaymentFromEmployeeSite(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- Scenario_5_FeeTypePaymentFromEmployeeSite -->
  <testcase name="Scenario_1_MakeCCPaymentwithPortalCredential" time="18.062" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <failure type="java.lang.AssertionError" message="Exception thrown, logout from  Admin KU Portal. Excep Msg&#039;Webmail&#039; column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown, logout from  Admin KU Portal. Excep Msg'Webmail' column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.logintoAdminPortal_Reset_Password(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_1_MakeCCPaymentwithPortalCredential(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- Scenario_1_MakeCCPaymentwithPortalCredential -->
  <testcase name="Scenario_10_EcheckEnableDisable" time="5.640" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <failure type="java.lang.AssertionError" message="Exception thrown, logout from  Admin KU Portal. Excep Msg&#039;Webmail&#039; column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown, logout from  Admin KU Portal. Excep Msg'Webmail' column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.logintoAdminPortal_Reset_Password(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_10_EcheckEnableDisable(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- Scenario_10_EcheckEnableDisable -->
  <testcase name="Scenario_9_SearchStudentInEmployeeSite" time="11.750" classname="com.PaymentCenterTestCases.PaymentCenterTestClass"/>
  <testcase name="Scenario_11_EmployeeSiteReports" time="40.001" classname="com.PaymentCenterTestCases.PaymentCenterTestClass"/>
  <testcase name="Scenario_4_makeOnetimePaymentwithoutLogin" time="54.407" classname="com.PaymentCenterTestCases.PaymentCenterTestClass"/>
  <testcase name="Scenario_6_ForgotPassword" time="16.329" classname="com.PaymentCenterTestCases.PaymentCenterTestClass"/>
  <testcase name="Scenario_8_ChangePassword" time="10.047" classname="com.PaymentCenterTestCases.PaymentCenterTestClass"/>
  <testcase name="Scenario_3_MakeECheck_PaymentwithPortalCredential" time="5.735" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <failure type="java.lang.AssertionError" message="Exception thrown, logout from  Admin KU Portal. Excep Msg&#039;Webmail&#039; column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown, logout from  Admin KU Portal. Excep Msg'Webmail' column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.logintoAdminPortal_Reset_Password(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_3_MakeECheck_PaymentwithPortalCredential(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.TestNG.privateMain(TestNG.java:1325)
	at org.testng.TestNG.main(TestNG.java:1294)
]]>
    </failure>
  </testcase> <!-- Scenario_3_MakeECheck_PaymentwithPortalCredential -->
</testsuite> <!-- com.PaymentCenterTestCases.PaymentCenterTestClass -->
